pipeline {
    agent {
        label 'Node1'
    }
    tools {
    maven 'Maven 3.6.3'
  }
    stages {
        stage('Build') {
            steps {
                sh 'python script.py'
                env.value=${sh(returnStdout: true, script: 'python script.py')}
                sh 'echo "$env.value"'
                sh 'mvn -B -DskipTests package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh "chmod +x -R ${env.WORKSPACE}"
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
